### ISSUE TITLE
[Windows 7] undefined method `default_mime_type=' for Sprockets::JstProcessor:Class

### ISSUE THREAD

**Issue by Javix** [sstephenson/sprockets#693]
I can't figure out why I have the following error when trying to run `rails s` on a Windows 7  x64 box:
```
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets/jst_processor.rb:5:in `<class:JstProcess
or>': undefined method `default_mime_type=' for Sprockets::JstProcessor:Class (NoMethodError)
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets/jst_processor.rb:4:in `<mod
ule:Sprockets>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets/jst_processor.rb:3:in `<top
 (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets/engines.rb:3:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets/engines.rb:3:in `<top (requ
ired)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets.rb:44:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets.rb:44:in `<module:Sprockets
>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets.rb:3:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.2.2/lib/sprockets/railtie.rb:5:in `requi
re'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.2.2/lib/sprockets/railtie.rb:5:in `<top
(required)>'
        from c:/Users/ZFTC0418/Documents/projects/rails_draft/config/application.rb:10:in `require'
        from c:/Users/ZFTC0418/Documents/projects/rails_draft/config/application.rb:10:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in
`require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in
`block in server'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in
`tap'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in
`server'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in
`run_command!'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required
)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
Reproduced with the following configuration:
- OS: Windows 7 x 64bits
- Ruby `ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]`
- sprockets version 2.12.3

The Gemfile has the line with therubyracer gem commented:
```
#gem 'therubyracer', platforms: :ruby
```
 I have node.js installed:
```
node -v
v0.10.35
```
and node gem too:
```
node (0.0.2)
```
Any idea on how to fix that ? Thank you.

**Comment by josh** [comment]
Can you post the version of "tilt" in your Gemfile.lock? 1.4.1 is the latest you should probably have.

**Comment by Javix** [comment]
Hey, Josh, the titl version in Gemfile.lock is 1.1 (see its complete content at this gist: https://gist.github.com/Javix/efa6192ae995e89db950). One more details I didn't mention: I had to install all Rails related gems locally by downloading them before one by one because of firewall and proxy restrictions applied on the projet (a real headache :) )

**Comment by Javix** [comment]
I've just deleted the Gemfile.lock fil and re-run `bundle install --local`. the newly generated Gemfile.lock is different from the previous one, see the new gist: https://gist.github.com/Javix/1430ae66cfca2aa3a6f9. Now I have no problem to start the server `rails s`. Thank you for your feed back; I'll close the issue.
