### ISSUE TITLE
fstat unimplemented unsupported or native support failed to load

### ISSUE THREAD

**Issue by cha55son** [sstephenson/sprockets#719]
Anyone have any clue why i'm getting this error from Sprockets 3.0.1?

```
NotImplementedError (fstat unimplemented unsupported or native support failed to load):
  org/jruby/RubyFile.java:1116:in `size'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cache/file_store.rb:110:in `set'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:274:in `atomic_write'
  org/jruby/RubyIO.java:1182:in `open'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:273:in `atomic_write'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cache/file_store.rb:108:in `set'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cache.rb:210:in `set'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cache.rb:86:in `fetch'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/base.rb:53:in `file_digest'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/loader.rb:160:in `fetch_asset_from_dependency_cache'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/loader.rb:33:in `load'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cached_environment.rb:20:in `initialize'
  org/jruby/RubyProc.java:290:in `call'
```

**Comment by cha55son** [comment]
Sorry wrong project.
